"""candidate keywords

Revision ID: 46c5e14924c5
Revises: 79f506a5e1b7
Create Date: 2025-07-17 06:10:47.036187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46c5e14924c5'
down_revision = '79f506a5e1b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('serp_result', sa.Column('total_weight', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('serp_result', sa.Column('metric_price', sa.Numeric(precision=3, scale=2), nullable=True))
    op.add_column('serp_result', sa.Column('metric_volume', sa.Numeric(precision=3, scale=2), nullable=True))
    op.add_column('serp_result', sa.Column('metric_site_size', sa.Numeric(precision=3, scale=2), nullable=True))
    op.add_column('serp_result', sa.Column('candidate_keyword', sa.JSON(), nullable=True))
    
    op.execute("ALTER TABLE serp_result MODIFY total_weight NUMERIC(5,2) NULL AFTER status;")
    op.execute("ALTER TABLE serp_result MODIFY metric_price NUMERIC(3,2) NULL AFTER site_size;")
    op.execute("ALTER TABLE serp_result MODIFY metric_volume NUMERIC(3,2) NULL AFTER metric_price;")
    op.execute("ALTER TABLE serp_result MODIFY metric_site_size NUMERIC(3,2) NULL AFTER metric_volume;")
    op.execute("ALTER TABLE serp_result MODIFY candidate_keyword JSON NULL AFTER metric_site_size;")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('serp_result', 'candidate_keyword')
    op.drop_column('serp_result', 'metric_size')
    op.drop_column('serp_result', 'metric_volume')
    op.drop_column('serp_result', 'metric_price')
    op.drop_column('serp_result', 'total_weight')
    # ### end Alembic commands ###
