"""add_is_hubspot_duplicate_column_in_serp_result_table

Revision ID: 55813b41ffe3
Revises: 46c5e14924c5
Create Date: 2025-08-26 09:36:31.072176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55813b41ffe3'
down_revision = '46c5e14924c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('serp_result', sa.Column('is_hubspot_duplicate', sa.Boolean(), server_default=sa.text('0'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('serp_result', 'is_hubspot_duplicate')
    # ### end Alembic commands ###
