"""initial_migration

Revision ID: 79f506a5e1b7
Revises: 
Create Date: 2025-07-16 03:54:55.902735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79f506a5e1b7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact_template',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('last', sa.String(length=100), nullable=True),
    sa.Column('first', sa.String(length=100), nullable=True),
    sa.Column('last_kana', sa.String(length=100), nullable=True),
    sa.Column('first_kana', sa.String(length=100), nullable=True),
    sa.Column('last_hira', sa.String(length=100), nullable=True),
    sa.Column('first_hira', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('department', sa.String(length=255), nullable=True),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.Column('phone1', sa.String(length=20), nullable=True),
    sa.Column('phone2', sa.String(length=20), nullable=True),
    sa.Column('phone3', sa.String(length=20), nullable=True),
    sa.Column('zip1', sa.String(length=10), nullable=True),
    sa.Column('zip2', sa.String(length=10), nullable=True),
    sa.Column('address1', sa.String(length=255), nullable=True),
    sa.Column('address2', sa.String(length=255), nullable=True),
    sa.Column('address3', sa.String(length=255), nullable=True),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('score_threshold',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('label', sa.String(length=1), nullable=False),
    sa.Column('value', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('label')
    )
    op.create_table('user_role',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('role_name', sa.Enum('sales_manager', 'sales_rep', 'system', name='role_name_enum'), nullable=False),
    sa.Column('typical_title', sa.String(length=100), nullable=True),
    sa.Column('responsibilities', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_name')
    )
    op.create_table('weighted_metric',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('value', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('label')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=True),
    sa.Column('password_hash', sa.String(length=60), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['user_role.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('batch_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('execution_type_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('duration', sa.Time(), server_default=sa.text("'00:00:00'"), nullable=False, comment='Duration (hh:mm:ss)'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hubspot_integration',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('hub_id', sa.BigInteger(), nullable=False),
    sa.Column('hub_domain', sa.String(length=100), nullable=False),
    sa.Column('refresh_token', sa.String(length=512), nullable=False),
    sa.Column('access_token', sa.String(length=512), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scopes', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('keyword',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('keyword', sa.String(length=100), nullable=False),
    sa.Column('fetch_status', sa.String(length=20), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('rank_status', sa.String(length=20), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('execution_date', sa.DateTime(), nullable=True),
    sa.Column('is_scheduled', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_keyword_term', 'keyword', ['keyword'], unique=False)
    op.create_index(op.f('ix_keyword_keyword'), 'keyword', ['keyword'], unique=True)
    op.create_table('batch_history_detail',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('keyword_id', sa.Integer(), nullable=True),
    sa.Column('target', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('error_message', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batch_history.id'], ),
    sa.ForeignKeyConstraint(['keyword_id'], ['keyword.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('serp_result',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('keyword_id', sa.Integer(), nullable=False),
    sa.Column('rank', sa.String(length=1), nullable=True, comment='Rank of the result in SERP (A, B, C)'),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('service_price', sa.BigInteger(), nullable=True),
    sa.Column('service_volume', sa.BigInteger(), nullable=True),
    sa.Column('site_size', sa.BigInteger(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('link', sa.String(length=2083), nullable=False),
    sa.Column('snippet', sa.Text(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False, comment='Position in SERP, 1-based'),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('domain_name', sa.String(length=255), nullable=True),
    sa.Column('contact_person', sa.String(length=255), nullable=True),
    sa.Column('phone_number', sa.String(length=32), nullable=True),
    sa.Column('url_corporate_site', sa.String(length=2083), nullable=True),
    sa.Column('url_service_site', sa.String(length=2083), nullable=True),
    sa.Column('email_address', sa.String(length=320), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('activity_date', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['keyword_id'], ['keyword.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ux_keyword_link', 'serp_result', ['keyword_id', 'link'], unique=True, mysql_length={'link': 191})
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ux_keyword_link', table_name='serp_result', mysql_length={'link': 191})
    op.drop_table('serp_result')
    op.drop_table('batch_history_detail')
    op.drop_index(op.f('ix_keyword_keyword'), table_name='keyword')
    op.drop_index('idx_keyword_term', table_name='keyword')
    op.drop_table('keyword')
    op.drop_table('hubspot_integration')
    op.drop_table('batch_history')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('weighted_metric')
    op.drop_table('user_role')
    op.drop_table('score_threshold')
    op.drop_table('contact_template')
    # ### end Alembic commands ###
