"""add_unique_constraint_to_sqs_message_id

Revision ID: e7df60fdd4f7
Revises: ff6277ee9a09
Create Date: 2025-10-01 03:47:29.878181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7df60fdd4f7'
down_revision = 'ff6277ee9a09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sqs_message_history_sqs_message_id', table_name='sqs_message_history')
    op.create_index(op.f('ix_sqs_message_history_sqs_message_id'), 'sqs_message_history', ['sqs_message_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sqs_message_history_sqs_message_id'), table_name='sqs_message_history')
    op.create_index('ix_sqs_message_history_sqs_message_id', 'sqs_message_history', ['sqs_message_id'], unique=False)
    # ### end Alembic commands ###
