"""increase_target_column_size_to_10000

Revision ID: ff6277ee9a09
Revises: 0b68692f4ea0
Create Date: 2025-10-01 03:22:07.363059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff6277ee9a09'
down_revision = '0b68692f4ea0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('batch_history_detail', 'target',
                    existing_type=sa.String(255),
                    type_=sa.String(10000),
                    existing_nullable=False)
    op.drop_index('ix_sqs_message_history_status', table_name='sqs_message_history')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_sqs_message_history_status', 'sqs_message_history', ['status'], unique=False)
    op.alter_column('batch_history_detail', 'target',
                    existing_type=sa.String(10000),
                    type_=sa.String(255),
                    existing_nullable=False)
    # ### end Alembic commands ###
